use_frameworks!

platform :ios, '9.0'

target 'DHTTableViewManager_Example' do
  pod 'DHTTableViewManager', :path => '../'
  pod 'SnapKit'

  target 'DHTTableViewManager_Tests' do
    inherit! :search_paths

    
  end
end
